[package]
name = "quinoa"
version = "0.1.0"
authors = ["RubenZx <ruben.mondom@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rocket = "0.4.2"
juniper = "0.14.2"
juniper_rocket = "0.5.2"